# Generated by Django 5.2.4 on 2025-07-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0002_jobposting_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
